FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /app
COPY . .
WORKDIR /app/src

RUN apt update
RUN apt install python3 python3-pip python3-opencv -y
RUN pip3 install tensorflow flask flask_cors scipy scikit-learn opencv-python

CMD ["python3", "face_rec_flask.py"]